webpage/models.py
from exts import db
from datetime import datetime
from sqlalchemy.dialects import mysql
from alembic import op
import sqlalchemy as sa

class UserModel(db.Model):
    __tablename__="user_data"
    id=db.Column(mysql.INTEGER(),primary_key=True,autoincrement=True, nullable=False, comment='用户id，唯一标识')
    name=db.Column( mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=False, unique=True,comment='用户名')
    nickname = db.Column(mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=True, comment='用户昵称，可重名')
    passwd = db.Column(mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='用户登录密码')
    phonenumber = db.Column(mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=11), nullable=True, comment='用户手机号码')
    create_time=db.Column(mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='用户创建时间')
    gender=db.Column(mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=6), nullable=True, comment='用户性别')
    balance=db.Column(mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='账户余额，单位为人民币')
    viplevel=db.Column(mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='vip等级')
    avatar=db.Column(mysql.MEDIUMBLOB(), nullable=True, comment='用户头像')



class QuestionModel(db.Model):
    __tablename__ = "question_data"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    author_id=db.Column(mysql.INTEGER(),db.ForeignKey("user_data.id"))
    create_time=db.Column(mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True)
    author=db.relationship("UserModel",backref="questions")


class AnswerModel(db.Model):
    __tablename__ = "answer_data"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True)
    question_id=db.Column(db.INTEGER,db.ForeignKey("question_data.id"))
    author_id = db.Column(mysql.INTEGER(), db.ForeignKey("user_data.id"))
    author = db.relationship("UserModel", backref="answers")
    question= db.relationship("QuestionModel",backref=db.backref("answers",order_by=create_time.desc()))

webpage/blueprints/forms.py
import wtforms
from wtforms.validators import length,EqualTo,InputRequired

class RegisterForm(wtforms.Form):
    name=wtforms.StringField(validators=[length(min=1,max=20)])
    password=wtforms.StringField(validators=[length(min=6,max=20)])
    password_confirm=wtforms.StringField(validators=[EqualTo("password")])

class LoginForm(wtforms.Form):
    name = wtforms.StringField(validators=[length(min=1, max=20)])
    password = wtforms.StringField(validators=[length(min=6, max=20)])


class QuestionForm(wtforms.Form):
    title=wtforms.StringField(validators=[length(min=3,max=200)])
    content= wtforms.StringField(validators=[length(min=5)])


class AnswerForm(wtforms.Form):
    content=wtforms.StringField(validators=[length(min=1)])
    question_id=wtforms.IntegerField(validators=[InputRequired()])

webpage/app.py
from flask import Flask,session,g
import config
from exts import db
from blueprints import qa_bp
from blueprints import user_bp
from flask_migrate import Migrate
from models import UserModel

app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)

migrate=Migrate(app,db)

app.register_blueprint(qa_bp)
app.register_blueprint(user_bp)



@app.before_request
def before_request():
    user_id=session.get("user_id")
    if user_id:
        try:
            user = UserModel.query.get(user_id)
            #给全局变量g绑定一个叫user的变量,其值是user
            #setattr(g,"user",user)
            g.user = user

        except:
            g.user=None
            pass

#请求到达之后-> before_request -> 视图函数 -> 视图函数中的返回模板 -> context_processor


@app.context_processor#上下文处理器
def context_processor():
    if hasattr(g,"user"):
        return {"user":g.user}
    else:
        return {}


if __name__ == '__main__':
    app.run(debug='TRUE')

webpage/blueprints/__init__.py
from .qa import bp as qa_bp
from .user import bp as user_bp

webpage/blueprints/qa.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,g
bp=Blueprint("qa",__name__,url_prefix="/")
from .forms import QuestionForm,AnswerForm
from models import QuestionModel,AnswerModel
from exts import db
from decorators import login_required
import os

from sqlalchemy import or_
@bp.route("/")
def index():
    questions=QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template("index.html",questions=questions)


@bp.route("/question/public",methods=['GET','POST'])
@login_required#判断是否登录
def public_question():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form=QuestionForm(request.form)
        if form.validate():
            title=form.title.data
            content=form.content.data
            question=QuestionModel(title=title,content=content,author=g.user)
            if(g.user.avatar):
                if(os.path.exists('webpage/static/images/'+g.user.name+'.png')==False):
                    fout=open('webpage/static/images/'+g.user.name+'.png','wb')
                    fout.write(g.user.avatar)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误！")
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question=QuestionModel.query.get(question_id)
    return render_template("detail.html",question=question)


@bp.route("/answer/<int:question_id>",methods=['POST'])
@login_required#判断是否登录
def answer(question_id):
    form=AnswerForm(request.form)
    if form.validate():
        content=form.content.data
        answer_model=AnswerModel(content=content,author=g.user,question_id=question_id)
        if (g.user.avatar):
            if (os.path.exists('webpage/static/images/' + g.user.name + '.png') == False):
                fout = open('webpage/static/images/' + g.user.name + '.png', 'wb')
                fout.write(g.user.avatar)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for('qa.question_detail',question_id=question_id))
    else:
        flash("评论格式错误！")
        return redirect(url_for('qa.question_detail',question_id=question_id))


@bp.route("/search")
def search():
    q=request.args.get("q")
    questions=QuestionModel.query.filter(or_(QuestionModel.title.contains(q),QuestionModel.content.contains(q))).order_by(db.text("-create_time"))
    return render_template("index.html",questions=questions)

webpage/blueprints/user.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session
from models import UserModel
from .forms import RegisterForm,LoginForm
from exts import db
import string
import random

bp=Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login",methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        form=LoginForm(request.form)
        if form.validate():
            name=form.name.data
            password=form.password.data
            user=UserModel.query.filter_by(name=name).first()
            if user and user.passwd == password:
                session["user_id"]=user.id
                return redirect("/")
            else:
                flash("用户名或密码错误！")
                return redirect(url_for("user.login"))
        else:
            flash("用户名或邮箱格式错误！")
            return redirect(url_for("user.login"))



@bp.route("/register",methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form=RegisterForm(request.form)
        if form.validate():
            username=form.name.data
            password=form.password.data
            user=UserModel(name=username,passwd=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))



@bp.route("/logout")
def logout():
    #清除所有数据
    session.clear()
    return redirect(url_for('user.login'))


@bp.route("/tutorial")
def tutorial():
    return render_template("tutorial.html")

webpage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}--{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand ml-5" href="#">DeepWeb</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('qa.index') }}">首页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问题</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"  href="{{ url_for('user.tutorial') }}">使用文档</a>
            </li>
            <li class="nav-item ml-3">
                <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
                    <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                </form>
            </li>

        </ul>
        <ul class="navbar-nav">
            {% if user %}
                <li class="nav-item">
                    <span class="nav-link">{{ user.nickname }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link mr-5" href="{{ url_for('user.logout') }}">退出登录</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.login') }}">登录<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mr-5" href="{{ url_for('user.register') }}">注册</a>
                </li>

            {% endif %}


        </ul>
    </div>
</nav>

<div class="container">
    {% block body %}{% endblock %}
</div>


</body>
</html>

webpage/templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}



{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}


{% block body %}
    <div class="row" style="margin-top: 20px">
        <div class="col"></div>
        <div class="col-8" style="background-color: #fff;padding:20px">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>提问者：{{ question.author.name }}</span>
                <span>提问时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">问题详情：{{ question.content }}</p>
            <hr>

            <h4 class="comment-group-title">评论（{{ question.answers|length }}）：</h4>
            <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
                <input type="hidden" name="question_id" value="{{ question.id }}">
                <div class="form-group">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}

                <div class="form-group" style="text-align: right">
                    <button class="btn btn-primary">评论</button>
                </div>
            </form>

            <ul class="comment-group">
                {% for answer in question.answers %}
                    <li>
                        <div class="user-info">
                            {% if question.author.avatar %}
                                <img class="avatar"
                                     src="{{ url_for('static',filename='images/'+answer.author.name+'.png') }}"
                                     alt="">
                            {% else %}
                                <img class="avatar" src="{{ url_for('static',filename='images/1.jpg') }}"
                                     alt="">
                            {% endif %}
                            <span class="username">{{ answer.author.nickname }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>



{% endblock %}

webpage/templates/index.html
{% extends "base.html" %}
{% block title %}DeepWeb-首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px">
        <div class="col"></div>
        <div class="col-8">
            <ul class="question-ul">
                {% for question in questions %}
                <li>
                    <div class="side-question">
                        {% if question.author.avatar %}
                            <img class="side-question-avatar" src="{{ url_for('static',filename='images/'+question.author.name+'.png') }}" alt="">
                        {% else %}
                            <img class="side-question-avatar" src="{{ url_for('static',filename='images/1.jpg') }}" alt="">
                        {% endif %}
                    </div>
                    <div class="question-main">
                        <div class="question-title "><a href="{{ url_for('qa.question_detail',question_id=question.id) }}">{{ question.title }}</a></div>
                        <div class="question-content">{{ question.content }}</div>
                        <div class="question-detail" style="text-align: right">
                            <span class="question-author">{{ question.author.nickname }}</span>
                            <span class="question-time">{{ question.create_time }}</span>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>

        </div>
        <div class="col"></div>
    </div>
{% endblock %}

webpage/templates/login.html
{% extends "base.html" %}
{% block title %}DeepWeb-登录{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method="POST" action="{{ url_for('user.login') }}">
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                </div>
            </form>
        </div>
         <div class="col"></div>
    </div>
{% endblock %}

webpage/templates/public_question.html
{% extends "base.html" %}

{% block title %}发布问题{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
    <h1 style="text-align: center">发布问题</h1>
    <form action="{{ url_for('qa.public_question') }}" method="post">
        <div class="form-group">
            <input type="text" name="title" class="form-control" placeholder="请输入标题">
        </div>
        <div class="form-group">
            <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
        </div>

        {% for message in get_flashed_messages() %}
            <div class="form-group">
                <div class="text-danger">{{ message }}</div>
            </div>
        {% endfor %}

        <div class="form-group" style="text-align: right">
            <button class="btn btn-primary">发布</button>
        </div>

    </form>
</div>
<div class="col"></div>

</div>



{% endblock %}

webpage/templates/register.html
{% extends "base.html" %}
{% block title %}DeepWeb-注册{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col"></div>
        <div class="col">
            <form method="POST" action="{{ url_for('user.register') }}">
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password_confirm">
                </div>
                <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

webpage/templates/tutorial.html
{% extends 'base.html' %}


{% block title %}DeepWeb-使用文档{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename=('css/tutorial.css'))}}">
{% endblock %}



{% block body %}
    <div class="row" style="margin-top: 15px">
        <div class="col"></div>
        <div class="col-8" style="background-color:#fff">
            <ul class="tutorial-ul">
                <li>
                    <h3 style="margin-top:15px ;text-align: center">功能介绍</h3>
                    <h5>整体系统</h5>
                    <p class="content">
                        整体系统核心构件如图所示,视频AI修复功能（包含上色和插帧两个子模块），视频AI增强功能（包括画质增强和超分），个人信息的管理（如更改用户名、密码等），普通版至Pro版的升级（会员的升级）；控制应用实现修复增强系统控制、账号控制、内容库控制、信息回显等相关功能，实现从传统的增强方案到基于深度学习的视频增强的重要转变。</p>
                    <h5>修复流程</h5>
                    <p class="content"> 如图所示，系统启动之后，会进行系统自检，如检测无误则读取相关配置，等待用户启动修复流程。
                        修复流程启动后，将从用户个人视频库中导入素材，分别进行噪声抑制、修复雪花点等修复流程，如果用户输入的视频为黑白视频，则会逐帧进行视频拆解，对食品进行插帧上色，然后输入，若用户需要4k超分功能且用户客户端为Pro版，则跳出Pro版专有的超分功能界面，由用户进行自定义的超分设置并开启超分增强功能，用户可实时预览超分过程，接着输出最后的视频。 </p>
                    <h5>增强流程</h5>
                    <p class="content">如图所示，当用户确认启动视频增强服务之后，会从用户个人本地视频库输入视频，进行画质增强、细节增强、SDR调色等增强功能，如果用户是Pro版用户，可以在Pro版超分增强界面提前配置并且选择是否需要超分功能，当进行超分时，会有基于GAN的超分辨率增强和HDR色彩修补，用户得到可以预览的超分视频界面，接着用户选择导出到本地视频库，增强结束。</p>
                </li>
                <br>
                <br>
                <li>
                    <h3 style="text-align: center">操作演示</h3>
                    <p class="content">1.软件主界面如下</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片1.png') }}" alt="">
                    <p class="content">2.在增强修复页面中，选择文件</p>
                    <img class="picture-file" src="{{ url_for('static',filename='images/tutorial/图片2.png') }}" alt="">
                    <p class="content">3.开始稳定修复，可以实时查看到结果</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片3.png') }}" alt="">
                    <p class="content">4.对视频修复也是同样的操作，右侧都可以设置相应的参数</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片4.png') }}" alt="">
                    <p class="content">5.任务进行中，中途可以终止任务</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片5.png') }}" alt="">
                    <p class="content">6.点击左侧用户选项卡，切换到用户界面</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片6.png') }}" alt="">
                    <p class="content">7.进行登录操作</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片7.png') }}" alt="">
                    <p class="content">8.登录后显示个人信息</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片8.png') }}" alt="">
                    <p class="content">9.可以对个人信息进行修改（点击“编辑信息”）</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片9.png') }}" alt="">
                    <p class="content">10.输入想要修改的信息，修改信息成功</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片10.png') }}" alt="">
                    <p class="content">11.VIP还可以使用超分增强服务</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片11.png') }}" alt="">
                    <p class="content">12.使用VIP等级足够的账号，进入VIP超分增强界面</p>
                    <img class="picture-file" src="{{ url_for('static',filename='images/tutorial/图片12.png') }}" alt="">
                    <p class="content">13.设置界面如下</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片13.png') }}" alt="">
                    <p class="content">14.可以修改主题</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片14.png') }}" alt="">
                    <p class="content">15.在帮助界面，可以点击按钮，启动浏览器跳转到网页端</p>
                    <img class="picture" src="{{ url_for('static',filename='images/tutorial/图片15.png') }}" alt="">
                    <p class="content">16.问题反馈与交流界面</p>
                    <img class="picture-file" src="{{ url_for('static',filename='images/tutorial/图片16.png') }}" alt="">
                </li>

            </ul>

        </div>
        <div class="col"></div>
    </div>


{% endblock %}